### ISSUE TITLE
Feature-request: vc search

### ISSUE THREAD

**Issue by matsimon** [adfinis-sygroup/vault-client#45]
If one doesn't know exactly what to look for, or only has remembers a keyword, a global 'vc search' command would be nice.

One downside I see however is that the audit log might get messed up. Possibly vc search shouldn't show the secrets, but only the name or tags.

Including the comments within the search would be excellent because sometimes it contains valuable extra keywords that might match.

**Comment by winpat** [comment]
Closed in favour of #32
