### ISSUE TITLE
Wrong auth config keys in readme

### ISSUE THREAD

**Issue by onitake** [adfinis-sygroup/vault-client#53]
The README lists the auth method parameters as:
```
backend_method: <ldap|token>
backend_auth: <ldap|token>
```

These should be:
```
auth_method
auth_backend
```

**Comment by winpat** [comment]
Thanks for reporting!

You are absolutely right, the README is wrong.
I will fix this right away.

**Comment by winpat** [comment]
Should be fixed now.
