### ISSUE TITLE
Copypasta

### ISSUE THREAD

**Issue by jefferai** [adfinis-sygroup/vault-client#7]
`insert.go` line 50 seems incorrect :-D

Noticed it in your demo gif.

**Comment by karras** [comment]
Thanks @jefferai ;)

@winpat can you also recreate the gif? I quickly checked all the strings and and found some smaller nitpickings:
* `delete.go` at line 53, whitespace
* `edit.go` at line 70, s/secrets/secret/
* `list.go` at line 73, s/Recusively/Recursively/
* `show.go` at line 28, s/The/There/
* `show.go` at line 47, s/it's/its/

**Comment by winpat** [comment]
Finally back from my holidays, thanks to both of you @jefferai and @karras.

Issue is fixed by #9
